server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: ms-video-encoder
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/database-video-encoder
    username: video-encoder
    password: video-encoder
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: local
    password: local
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT}
      region:
        static: us-east-1
      credentials:
        access-key: key
        secret-key: key
      s3:
        enabled: true
        config:
          enabled: true
        region: us-east-1
        endpoint: ${AWS_S3_ENDPOINT}
  threads:
    virtual:
      enabled: true

ms-video-encoder:
  tmp-dir: tmp
  bucket: videoencoder
  input-path: uploaded-video
  output-path: processed-video
